name:           FandomFest 2014
description:    FandomFest is basically a summer festival of all your favorite TV/movie fandoms, so come on, turn your laptop off for a few hours and get out of the house for some fun with your fellow enthusiasts.

permalink:      pretty
