# Page details
name:           FandomFest 2014
description:    "FandomFest is basically a summer festival of all your favorite TV/movie fandoms, so come on, turn your laptop off for a few hours and get out of the house for some fun with your fellow enthusiasts."
author:
  name:         Resi Respati
  twitter:      https://twitter.com/resir014
  email:        resir014@gmail.com

# Properties
permalink:      pretty
exclude:        ["Makefile", "Gruntfile.js", "README.md", "less", "node_modules", "package.json"]
url:            https://resir014.github.io
baseurl:        "/fandom-fest"

# Server
host:           0.0.0.0
port:           4000
url:            http://fandom-fest.com
encoding:       UTF-8
